-- ============================================================
-- Contract Master — version history (applied 2026-09-24), used by js/contract-tools.js (History → Restore)
--   * every website change (add / edit / delete, i.e. auth.uid() is set) is stored in contract_history
--     (op, row_id, kind, old_data, new_data, changed_at, changed_by); deleted rows also go to contract_deleted
--   * imports (pg_cron worker, no user) are not logged here — they keep contract_backup
--   * contract_restore(history_id): UPDATE → old values back · DELETE → row re-inserted · INSERT → added row removed
--   * pg_cron job "contract_history_cleanup" (03:15 daily) deletes history / deleted rows older than 7 days
--   * TYPE OF CONTRACT normalised to upper case (e.g. "New Outlet" / "New OUTLET" → NEW OUTLET)
-- Live definitions: select pg_get_functiondef('contract_log_change'::regproc), pg_get_functiondef('contract_restore'::regproc);
-- ============================================================
CREATE TABLE IF NOT EXISTS public.contract_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  op text NOT NULL, row_id bigint, kind text,
  old_data jsonb, new_data jsonb,
  changed_at timestamptz NOT NULL DEFAULT now(), changed_by text
);
CREATE INDEX IF NOT EXISTS contract_history_at_idx ON public.contract_history (changed_at DESC);
ALTER TABLE public.contract_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Signed-in users read contract history" ON public.contract_history FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL);
-- triggers: contract_log_change_del (BEFORE DELETE), contract_log_change_row (AFTER INSERT OR UPDATE) → contract_log_change()
-- cron: select cron.schedule('contract_history_cleanup', '15 3 * * *',
--   $$DELETE FROM public.contract_history WHERE changed_at < now() - interval '7 days';
--     DELETE FROM public.contract_deleted WHERE deleted_at < now() - interval '7 days'$$);
