-- ============================================================
-- Data Universe — monthly Excel import pipeline (applied 2026-09-23)
--
-- How it works (Data Universe page → Import):
--   1. the website reads the Excel file (.xlsx / .xlsm), finds the header row,
--      maps Excel names to Supabase names and uploads rows to data_u_staging
--   2. it calls data_u_request_replace(batch) → a job row in data_u_import_jobs
--   3. pg_cron runs data_u_process_import_jobs() every minute as the DB owner
--      (no 8-second API limit): backup current rows → TRUNCATE → insert staged rows
--      Blank Company / Group values keep their current value (matched by Outlet Code).
--      Refuses if the file has less than half of the current rows.
--   4. the page polls the job until status = done / error
--
-- Restore a backup (example):
--   TRUNCATE "Data Universe";
--   INSERT INTO "Data Universe" (<cols>) SELECT <cols> FROM data_u_backup WHERE batch_id = '<batch>';
-- ============================================================

-- New columns from the monthly file + real row id
ALTER TABLE public."Data Universe"
  ADD COLUMN IF NOT EXISTS "Current BDE"      text,
  ADD COLUMN IF NOT EXISTS "Catalogue Status" text,
  ADD COLUMN IF NOT EXISTS "Contract Flag"    text;   -- Excel "Contract" (YES/NO)

CREATE TABLE IF NOT EXISTS public.data_u_staging (LIKE public."Data Universe");
ALTER TABLE public.data_u_staging
  ADD COLUMN IF NOT EXISTS batch_id  text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS loaded_at timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS data_u_staging_batch_idx ON public.data_u_staging (batch_id);

CREATE TABLE IF NOT EXISTS public.data_u_backup (LIKE public."Data Universe");
ALTER TABLE public.data_u_backup
  ADD COLUMN IF NOT EXISTS batch_id  text,
  ADD COLUMN IF NOT EXISTS backup_at timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS data_u_backup_batch_idx ON public.data_u_backup (batch_id);

ALTER TABLE public."Data Universe"
  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE public.data_u_staging ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.data_u_backup  ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Signed-in users manage staging" ON public.data_u_staging
  FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Signed-in users manage backup" ON public.data_u_backup
  FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
REVOKE ALL ON public.data_u_staging, public.data_u_backup FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.data_u_staging, public.data_u_backup TO authenticated;

-- Jobs + background worker
CREATE EXTENSION IF NOT EXISTS pg_cron;

CREATE TABLE IF NOT EXISTS public.data_u_import_jobs (
  batch_id text PRIMARY KEY, status text NOT NULL DEFAULT 'queued',
  file_name text, staged_rows int, previous_rows int, new_rows int, message text,
  requested_by text, requested_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz, finished_at timestamptz
);
ALTER TABLE public.data_u_import_jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Signed-in users read import jobs" ON public.data_u_import_jobs
  FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL);
REVOKE ALL ON public.data_u_import_jobs FROM anon, authenticated;
GRANT SELECT ON public.data_u_import_jobs TO authenticated;

CREATE OR REPLACE FUNCTION public.data_u_replace_from_staging(p_batch text, p_force boolean DEFAULT false)
 RETURNS json LANGUAGE plpgsql SET search_path TO 'public' SET enable_nestloop TO 'off'
AS $function$
DECLARE
  n_new int; n_old int; cols text;
BEGIN
  SELECT count(*) INTO n_new FROM data_u_staging WHERE batch_id = p_batch;
  SELECT count(*) INTO n_old FROM "Data Universe";
  IF n_new = 0 THEN
    RAISE EXCEPTION 'No uploaded rows found for this import.';
  END IF;
  IF NOT p_force AND n_new < n_old * 0.5 THEN
    RAISE EXCEPTION 'The file has % rows but Data Universe has % (less than half). Import stopped to protect your data.', n_new, n_old;
  END IF;

  -- keep existing Company / Group values when the file leaves them blank (match by Outlet Code)
  UPDATE data_u_staging s SET
    "Company Name" = coalesce(nullif(trim(s."Company Name"), ''), o.company),
    "Group Name"   = coalesce(nullif(trim(s."Group Name"),   ''), o.gname),
    "Group Code"   = coalesce(nullif(trim(s."Group Code"),   ''), o.gcode)
  FROM (
    SELECT upper(trim("Outlet Code")) AS code,
           max(nullif(trim("Company Name"), '')) AS company,
           max(nullif(trim("Group Name"),   '')) AS gname,
           max(nullif(trim("Group Code"),   '')) AS gcode
    FROM "Data Universe" GROUP BY 1
  ) o
  WHERE s.batch_id = p_batch AND upper(trim(s."Outlet Code")) = o.code;

  SELECT string_agg(quote_ident(column_name), ', ' ORDER BY ordinal_position) INTO cols
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'data_u_staging'
    AND column_name NOT IN ('batch_id', 'loaded_at', 'id');

  EXECUTE format('INSERT INTO data_u_backup (%s, batch_id, backup_at) SELECT %s, %L, now() FROM "Data Universe"', cols, cols, p_batch);
  TRUNCATE "Data Universe";
  EXECUTE format('INSERT INTO "Data Universe" (%s) SELECT %s FROM data_u_staging WHERE batch_id = %L', cols, cols, p_batch);
  DELETE FROM data_u_staging WHERE batch_id = p_batch;

  -- keep only the 3 most recent backups
  DELETE FROM data_u_backup
  WHERE batch_id NOT IN (SELECT batch_id FROM data_u_backup GROUP BY batch_id ORDER BY max(backup_at) DESC LIMIT 3);

  RETURN json_build_object('previous_rows', n_old, 'new_rows', n_new);
END $function$;
REVOKE ALL ON FUNCTION public.data_u_replace_from_staging(text, boolean) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.data_u_request_replace(p_batch text, p_file text DEFAULT NULL::text)
 RETURNS json LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE n int;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Please sign in first.'; END IF;
  SELECT count(*) INTO n FROM data_u_staging WHERE batch_id = p_batch;
  IF n = 0 THEN RAISE EXCEPTION 'No uploaded rows found for this import.'; END IF;
  IF EXISTS (SELECT 1 FROM data_u_import_jobs WHERE status IN ('queued','running')) THEN
    RAISE EXCEPTION 'Another import is already waiting or running. Please wait for it to finish.';
  END IF;
  INSERT INTO data_u_import_jobs (batch_id, file_name, staged_rows, requested_by)
  VALUES (p_batch, p_file, n, auth.jwt() ->> 'email');
  RETURN json_build_object('batch_id', p_batch, 'staged_rows', n, 'status', 'queued');
END $function$;
REVOKE ALL ON FUNCTION public.data_u_request_replace(text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.data_u_request_replace(text, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.data_u_process_import_jobs()
 RETURNS void LANGUAGE plpgsql SET search_path TO 'public'
AS $function$
DECLARE j record; r json;
BEGIN
  -- tidy abandoned uploads (staged but never queued) after 1 day
  DELETE FROM data_u_staging s WHERE loaded_at < now() - interval '1 day'
    AND NOT EXISTS (SELECT 1 FROM data_u_import_jobs q WHERE q.batch_id = s.batch_id AND q.status IN ('queued','running'));

  SELECT * INTO j FROM data_u_import_jobs WHERE status = 'queued' ORDER BY requested_at LIMIT 1 FOR UPDATE SKIP LOCKED;
  IF NOT FOUND THEN RETURN; END IF;
  UPDATE data_u_import_jobs SET status = 'running', started_at = now() WHERE batch_id = j.batch_id;

  BEGIN
    r := data_u_replace_from_staging(j.batch_id);
    UPDATE data_u_import_jobs SET status = 'done', finished_at = now(),
      previous_rows = (r->>'previous_rows')::int, new_rows = (r->>'new_rows')::int,
      message = 'Import complete'
    WHERE batch_id = j.batch_id;
  EXCEPTION WHEN OTHERS THEN
    UPDATE data_u_import_jobs SET status = 'error', finished_at = now(), message = SQLERRM WHERE batch_id = j.batch_id;
    DELETE FROM data_u_staging WHERE batch_id = j.batch_id;
  END;
END $function$;
REVOKE ALL ON FUNCTION public.data_u_process_import_jobs() FROM PUBLIC, anon, authenticated;

SELECT cron.schedule('data-u-import-worker', '* * * * *', 'SELECT public.data_u_process_import_jobs()');
